version: "3"

services:

  ### content service
  content:
    image: schulcloud/schulcloud-content
    build: content/content-api
    environment:
      BACKEND_URL: https://server:9000/
    ports:
      - "4040"
    depends_on:
      - content-mongodb
      - content-elasticsearch
    links:
      - content-mongodb:mongodb
      - content-elasticsearch:elasticsearch
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      placement:
        constraints:
          - node.labels.node_type != db
    restart: always
  
  content-mongodb:
    image: mongo:3.4.3
    volumes:
      - data-schulcloud-content:/data/db
    ports:
      - "27018"
    deploy:
      placement:
        constraints:
          - node == databases
    command: [ "--replSet", "rs" ]

  content-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms6144m -Xmx6144m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-schulcloud-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200"
    deploy:
      placement:
        constraints:
          - node == elasticsearch

  content-mongo-connector:
    image: schulcloud/schulcloud-content-mongo-connector
    build: content/content-mongo-connector
    depends_on:
      - content-mongodb
      - content-elasticsearch
    links:
      - content-mongodb:mongodb
      - content-elasticsearch:elasticsearch
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      placement:
        constraints:
          - node.labels.node_type != db