version: "3"

services:
  postgres:
    image: postgres:9.5
    ports:
      - "5432"
    volumes:
      - 'data-calendar:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=schulcloud_calendar
      - POSTGRES_USER=node
      - POSTGRES_PASSWORD=genericpassword
    deploy:
      placement:
        constraints:
          - node == docker-swarm-4
    restart: always

  web-calendar:
    image: langleu/schulcloud-calendar
    build: calendar-api
    ports:
      - "3000"
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - DB_PASSWORD=genericpassword
      - DB_HOST=postgres
      - DB_USERNAME=node
      - DB_DATABASE=schulcloud_calendar
      - SCHULCLOUD_BASE_PATH=http://server:9000
      - NOTIFICATION_SERVICE_BASE_PATH=http://notification:3030
      - SCHULCLOUD_ALL_USERS_FOR_UUID=http://server:9000/resolve/users/
      - SCHULCLOUD_ALL_SCOPES_FOR_TOKEN=http://server:9000/resolve/scopes/
      - NOTIFICATION_SERVICE_NEW_NOTIFICATION=http://notification:3030/messages
      - NODE_ENV=production
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      placement:
        constraints:
          - node.labels.node_type != db
    restart: always

volumes:
  data-calendar:
