apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mongodbsc
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mongodbsc
    spec:
      containers:
      - image: mongo:3.4
        name: mongodbsc
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: data-sc
      restartPolicy: Always
      volumes:
      - name: data-sc
        persistentVolumeClaim:
          claimName: data-sc
status: {}
