apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mongodbsc
  name: mongodbsc
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: mongodbsc
status:
  loadBalancer: {}
