apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mongo-connector
  name: mongo-connector
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: mongo-connector
status:
  loadBalancer: {}
