apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: schulcloud_calendar
        - name: POSTGRES_USER
          value: node
        - name: PGDATA
          value: /var/lib/postgresql/data/pq
        image: postgres:9.5
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data-calendar
      restartPolicy: Always
      volumes:
      - name: data-calendar
        persistentVolumeClaim:
          claimName: data-calendar
status: {}
