apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: server
  name: server
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: server
status:
  loadBalancer: {}
