apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: web-calendar
  name: web-calendar
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    service: web-calendar
status:
  loadBalancer: {}
