apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: web-content
  name: web-content
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8090
  selector:
    service: web-content
status:
  loadBalancer: {}
