apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: web-crawler
  name: web-crawler
spec:
  ports:
  - name: "8091"
    port: 8091
    targetPort: 8091
  selector:
    service: web-crawler
status:
  loadBalancer: {}
